### ISSUE TITLE
Initial conditions  +  Figure 3

### ISSUE THREAD

**Issue by ElodieBsq** [BIO6032/2019_replication_HastingsPowell_1991#5]
### Initial conditions (u0 for x,y,z)###

We have to figure out which initial conditions to use for u0 (x,y,z), considering it is not mentionned in the paper. 

It is important for all the figures (2,4 and 5) but especially for figure 3 because the initial conditions have a huge impact on the look of the graph. 

With the **figure 3** in the paper, I knew that x was around  0.75. Since x was the same in figure 2a, I chose y and z values based on figure 2b and 2c. It's only an estimation based on the graphs and I tried to adjust it to have a similar figure 3.  For now, the best I have is **u0= [0.75, 0.15, 9.75]**. But it still not perfectly the same as in the paper. 

We could see with @BIO6032/dreamteam if they have any idea how we should choose the initial conditions?

**Comment by tpoisot** [comment]
If the initial conditions are not in the paper, you are pretty much toast. The only thing you can do is try to guess, because if the system is even a little bit chaotic, you will never get the same figure unless you pick the exact same solution (and even then, you would need to have the exact same integration algorithm). This will be a point to discuss in the manuscript.
