### ISSUE TITLE
Figure 4 (c) - Steps

### ISSUE THREAD

**Issue by FrancisBanville** [BIO6032/2019_replication_HastingsPowell_1991#9]
Hastings and Powell used steps of 0.01 unit of b1 when they created their Figure 4. I think we should make our replication with the same steps, and see if it makes it more like theirs! 👽

**Comment by gabrieldansereau** [comment]
Actually, we do use steps of 0.01 to replicate figure 4. In fact, we use steps of 0.01 between all b1 values, whereas H&P used steps of 0.01 between 2.0 and 3.2 and steps of 0.1 between 3.2 and 6.2. 

>" We used values of b1 between 2.0 and 3.2, changing b1 in steps of 0.01, and values of b1 from 3.2 to 6.2, changing b1 in steps of 0.1. " (p.899)

There's something weird about that, because they seem to have used steps 0.01 for all values in their figure 4b. Anyways, our approach allows us to have figures very similar to 4a and 4b, so we should keep it this way.

As for figure 4c, there's something funny there too, since they seem to have used smaller steps than 0.01. I tried using steps of 0.001 and 0.005. Here's the results: 

Steps of 0.001
![fig4c_001](https://user-images.githubusercontent.com/37338144/56693326-260b5700-66b2-11e9-8722-e88d5fae97cd.png)

Steps of 0.005
![fig4c_005](https://user-images.githubusercontent.com/37338144/56693417-666ad500-66b2-11e9-9891-c7ffe0c59b03.png)

And steps of 0.01, which we already had, for comparison's sake
![fig4c](https://user-images.githubusercontent.com/37338144/56693485-91edbf80-66b2-11e9-80f0-a826c08ecbf9.png)

Maybe the smaller steps do give better results, but it's never the same as in H&P. They might have used a different method. That or the resolution in the original paper is so terrible that we don't see the figure correctly.

**Comment by ElodieBsq** [comment]
I think we should keep the same timesteps that H&P said they used, even if it's not the one that looks better. And then, we could investigate / propose hypothsesis on why ours doesn't look like theirs.
